apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: {{ .Values.deployment.image.username }}/{{ .Values.deployment.image.registry }}:{{ .Values.deployment.image.tag }}
          name: {{ .Chart.Name }}-{{ .Release.Name }}
          ports:
          - containerPort: {{ .Values.service.targetPort }}
      imagePullSecrets:
        - name: my-secret
