apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
   - port: {{ .Values.service.port }}
     targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
